'use client';

import { FormEvent, useState } from 'react';

type Weights = { baseScore:number;activityMatch:number;activityMiss:number;areaMatch:number;areaMiss:number;timeMatch:number;timeMiss:number;groupMatch:number;ageMatch:number;ageMiss:number;languageMatch:number;safetyPenalty:number };
type Config = { id:string;version:string;status:'DRAFT'|'ACTIVE'|'ARCHIVED';weights:Weights;note:string;createdBy:string;activatedBy:string|null;activatedAt:string|null;createdAt:string };
type Dashboard = { activeVersion:string;defaults:Weights;metrics:{users:number;hangouts:number;completed:number;averageRating:number|null;ratingCount:number;reports:number};feedback:Array<{algorithmVersion:string;outcome:string;_count:{_all:number}}>;configs:Config[] };
type Action = { id:string;action:string;reason:string;adminId:string;createdAt:string };
type Report = { id:string;reason:string;details:string|null;status:string;reporter:{displayName:string};targetUser:{displayName:string;accountStatus:string};hangout:{title:string}|null;actions:Action[] };
const API=process.env.NEXT_PUBLIC_API_URL??'https://hangoutnow-api.onrender.com';
const labels:Record<keyof Weights,string>={baseScore:'基準スコア',activityMatch:'活動一致',activityMiss:'活動不一致',areaMatch:'エリア一致',areaMiss:'エリア不一致',timeMatch:'時間一致',timeMiss:'時間不一致',groupMatch:'人数一致',ageMatch:'年齢一致',ageMiss:'年齢不一致',languageMatch:'言語一致',safetyPenalty:'安全措置1件の減点'};

export default function AdminHome(){
 const[token,setToken]=useState('');const[adminId,setAdminId]=useState('');const[data,setData]=useState<Dashboard|null>(null);const[reports,setReports]=useState<Report[]>([]);const[error,setError]=useState('');const[version,setVersion]=useState('match-v1.2.0');const[note,setNote]=useState('');const[weights,setWeights]=useState<Weights|null>(null);
 const headers={'content-type':'application/json','x-admin-token':token,'x-admin-id':adminId};
 async function load(event?:FormEvent){event?.preventDefault();setError('');const[m,r]=await Promise.all([fetch(`${API}/admin/matching`,{headers,cache:'no-store'}),fetch(`${API}/admin/reports`,{headers,cache:'no-store'})]);if(!m.ok||!r.ok){setError('認証またはデータ取得に失敗しました');return}const dashboard=await m.json() as Dashboard;setData(dashboard);setWeights(current=>current??dashboard.defaults);setReports(await r.json() as Report[])}
 async function saveDraft(event:FormEvent){event.preventDefault();if(!weights)return;const response=await fetch(`${API}/admin/matching/configs`,{method:'POST',headers,body:JSON.stringify({version,note,weights})});if(!response.ok){setError((await response.json().catch(()=>null))?.message??'下書きを保存できませんでした');return}setNote('');await load()}
 async function activate(config:Config){if(!window.confirm(`${config.version} を全ユーザーのマッチングに適用しますか？`))return;const response=await fetch(`${API}/admin/matching/configs/${config.id}/activate`,{method:'POST',headers});if(!response.ok){setError('有効化できませんでした');return}await load()}
 async function act(id:string,action:string){const reason=window.prompt('措置理由（監査履歴に保存）');if(!reason)return;await fetch(`${API}/admin/reports/${id}/actions`,{method:'POST',headers,body:JSON.stringify({action,reason})});await load()}
 const card={border:'1px solid #dce3dd',borderRadius:16,padding:18,marginTop:16,background:'#fff'} as const;
 return <main style={{maxWidth:1180,margin:'0 auto',padding:24,fontFamily:'sans-serif',color:'#17221d',background:'#f6f8f6'}}><h1>Hangout Now 運営管理</h1><form onSubmit={load} style={{display:'flex',gap:8,flexWrap:'wrap'}}><input aria-label="管理トークン" type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="管理トークン" required/><input aria-label="担当者ID" value={adminId} onChange={e=>setAdminId(e.target.value)} placeholder="担当者ID" maxLength={100} required/><button>管理データを取得</button></form>{error&&<p role="alert" style={{color:'#a32f20'}}>{error}</p>}
 {data&&<><section style={card}><h2>マッチング状況</h2><p><b>有効バージョン：</b>{data.activeVersion}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{[['ユーザー',data.metrics.users],['Hangout',data.metrics.hangouts],['開催完了',data.metrics.completed],['平均評価',data.metrics.averageRating?.toFixed(2)??'—'],['評価件数',data.metrics.ratingCount],['通報',data.metrics.reports]].map(([label,value])=><div key={label} style={{padding:12,background:'#eef4ef',borderRadius:10}}><small>{label}</small><strong style={{display:'block',fontSize:24}}>{value}</strong></div>)}</div><h3>バージョン別フィードバック</h3><ul>{data.feedback.map(item=><li key={`${item.algorithmVersion}-${item.outcome}`}>{item.algorithmVersion} / {item.outcome}: {item._count._all}件</li>)}</ul></section>
 <section style={card}><h2>アルゴリズム設定</h2><p>まず下書きを保存し、内容を確認してから有効化してください。過去バージョンは監査履歴として残ります。</p>{weights&&<form onSubmit={saveDraft}><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><label>新バージョン<input value={version} onChange={e=>setVersion(e.target.value)} pattern="match-v[0-9]+\.[0-9]+\.[0-9]+" required/></label><label style={{flex:1}}>変更理由<input value={note} onChange={e=>setNote(e.target.value)} maxLength={300} required style={{width:'100%'}}/></label></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:16}}>{(Object.keys(labels) as Array<keyof Weights>).map(key=><label key={key}>{labels[key]}<input type="number" value={weights[key]} onChange={e=>setWeights({...weights,[key]:Number(e.target.value)})} style={{display:'block',width:'100%'}} required/></label>)}</div><button style={{marginTop:14}}>下書きを保存</button></form>}<h3>変更履歴</h3>{data.configs.length===0?<p>DB設定はまだありません。現在はコード内の初期値で動作しています。</p>:data.configs.map(config=><article key={config.id} style={{borderTop:'1px solid #ddd',padding:'12px 0'}}><b>{config.version}・{config.status}</b><p>{config.note}<br/><small>作成: {config.createdBy} / {new Date(config.createdAt).toLocaleString('ja-JP')}{config.activatedBy?`　有効化: ${config.activatedBy}`:''}</small></p>{config.status==='DRAFT'&&<button onClick={()=>void activate(config)}>このバージョンを有効化</button>}</article>)}</section></>}
 {data&&<section style={card}><h2>安全管理</h2>{reports.map(report=><article key={report.id} style={{borderTop:'1px solid #ddd',padding:'12px 0'}}><b>{report.reason}・{report.status}</b><p>通報者: {report.reporter.displayName} / 対象: {report.targetUser.displayName}（{report.targetUser.accountStatus}）<br/>{report.hangout?.title??'Hangout指定なし'} / {report.details??'詳細なし'}</p><div style={{display:'flex',gap:8}}><button onClick={()=>void act(report.id,'WARNING')}>警告</button><button onClick={()=>void act(report.id,'SUSPEND')}>一時停止</button><button onClick={()=>void act(report.id,'BAN')}>永久停止</button></div></article>)}</section>}</main>;
}
