'use client';

import { FormEvent, useState } from 'react';

type Weights = { baseScore:number;activityMatch:number;activityMiss:number;areaMatch:number;areaMiss:number;timeMatch:number;timeMiss:number;groupMatch:number;ageMatch:number;ageMiss:number;languageMatch:number;safetyPenalty:number };
type Config = { id:string;version:string;status:'DRAFT'|'ACTIVE'|'ARCHIVED';weights:Weights;note:string;createdBy:string;activatedBy:string|null;activatedAt:string|null;createdAt:string };
type CountRow<K extends string> = Record<K,string|number|null>&{_count:{_all:number}};
type Dashboard = { activeVersion:string;defaults:Weights;metrics:{users:number;registeredUsers:number;activeUsers:{day:number;week:number;month:number};hangouts:number;completed:number;averageRating:number|null;ratingCount:number;reports:number};feedback:Array<CountRow<'algorithmVersion'|'outcome'>>;funnel:Array<CountRow<'eventType'>>;ratingDistribution:Array<CountRow<'score'>>;declineReasons:Array<CountRow<'reason'>>;configs:Config[] };
type Action = { id:string;action:string;reason:string;adminId:string;createdAt:string };
type Report = { id:string;reason:string;details:string|null;status:string;reporter:{displayName:string};targetUser:{displayName:string;accountStatus:string};hangout:{title:string}|null;actions:Action[] };
type PushOverview = { paused:boolean;updatedAt:string|null;registeredTokens:number;platforms:Array<{platform:string;_count:{_all:number}}>;deliveries:Array<{status:string;_count:{_all:number}}> };
const API=process.env.NEXT_PUBLIC_API_URL??'https://hangoutnow-api.onrender.com';
const labels:Record<keyof Weights,string>={baseScore:'基準スコア',activityMatch:'活動一致',activityMiss:'活動不一致',areaMatch:'エリア一致',areaMiss:'エリア不一致',timeMatch:'時間一致',timeMiss:'時間不一致',groupMatch:'人数一致',ageMatch:'年齢一致',ageMiss:'年齢不一致',languageMatch:'言語一致',safetyPenalty:'安全措置1件の減点'};
const funnelLabels:Record<string,string>={HANGOUT_VIEWED:'詳細閲覧',JOIN_REQUESTED:'参加申請',JOIN_ACCEPTED:'承認',HANGOUT_CREATED:'募集作成',HANGOUT_COMPLETED:'開催完了'};
const reasonLabels:Record<string,string>={TIME:'時間が合わない',DISTANCE:'距離が合わない',FULL:'満員',BUDGET:'予算が合わない',CONDITIONS:'参加条件が合わない',OTHER:'その他'};

function Bars({items,color='#176b48'}:{items:Array<{label:string;value:number}>;color?:string}){const max=Math.max(1,...items.map(item=>item.value));return <div style={{display:'grid',gap:10}}>{items.map(item=><div key={item.label} style={{display:'grid',gridTemplateColumns:'120px 1fr 54px',alignItems:'center',gap:10}}><small>{item.label}</small><div style={{height:12,borderRadius:999,background:'#e7ece8',overflow:'hidden'}}><div style={{width:`${Math.max(item.value>0?3:0,item.value/max*100)}%`,height:'100%',borderRadius:999,background:color}}/></div><b style={{textAlign:'right'}}>{item.value}</b></div>)}</div>}

export default function AdminHome(){
 const[token,setToken]=useState('');const[adminId,setAdminId]=useState('');const[data,setData]=useState<Dashboard|null>(null);const[reports,setReports]=useState<Report[]>([]);const[push,setPush]=useState<PushOverview|null>(null);const[error,setError]=useState('');const[version,setVersion]=useState('match-v1.2.0');const[note,setNote]=useState('');const[weights,setWeights]=useState<Weights|null>(null);const[testUserId,setTestUserId]=useState('');
 const headers={'content-type':'application/json','x-admin-token':token,'x-admin-id':adminId};
 async function load(event?:FormEvent){event?.preventDefault();setError('');const[m,r,p]=await Promise.all([fetch(`${API}/admin/matching`,{headers,cache:'no-store'}),fetch(`${API}/admin/reports`,{headers,cache:'no-store'}),fetch(`${API}/admin/notifications`,{headers,cache:'no-store'})]);if(!m.ok||!r.ok||!p.ok){setError('認証またはデータ取得に失敗しました');return}const dashboard=await m.json() as Dashboard;setData(dashboard);setWeights(current=>current??dashboard.defaults);setReports(await r.json() as Report[]);setPush(await p.json() as PushOverview)}
 async function saveDraft(event:FormEvent){event.preventDefault();if(!weights)return;const response=await fetch(`${API}/admin/matching/configs`,{method:'POST',headers,body:JSON.stringify({version,note,weights})});if(!response.ok){setError((await response.json().catch(()=>null))?.message??'下書きを保存できませんでした');return}setNote('');await load()}
 async function activate(config:Config){if(!window.confirm(`${config.version} を全ユーザーのマッチングに適用しますか？`))return;const response=await fetch(`${API}/admin/matching/configs/${config.id}/activate`,{method:'POST',headers});if(!response.ok){setError('有効化できませんでした');return}await load()}
 async function act(id:string,action:string){const reason=window.prompt('措置理由（監査履歴に保存）');if(!reason)return;await fetch(`${API}/admin/reports/${id}/actions`,{method:'POST',headers,body:JSON.stringify({action,reason})});await load()}
 async function pausePush(paused:boolean){if(!window.confirm(paused?'すべてのプッシュ配信を停止しますか？':'プッシュ配信を再開しますか？'))return;await fetch(`${API}/admin/notifications/pause`,{method:'POST',headers,body:JSON.stringify({paused})});await load()}
 async function cleanupTokens(){if(!window.confirm('90日以上更新されていない端末トークンを削除しますか？'))return;await fetch(`${API}/admin/notifications/cleanup`,{method:'POST',headers});await load()}
 async function sendTestPush(event:FormEvent){event.preventDefault();const response=await fetch(`${API}/admin/notifications/test`,{method:'POST',headers,body:JSON.stringify({userId:testUserId,title:'Hangout Now テスト通知',body:'プッシュ通知の受信テストです。'})});if(!response.ok){setError('テスト通知を送信できませんでした');return}window.alert('テスト通知をキューへ登録しました')}
 const card={border:'1px solid #dce3dd',borderRadius:16,padding:18,marginTop:16,background:'#fff'} as const;
 const funnelItems=data?['HANGOUT_VIEWED','JOIN_REQUESTED','JOIN_ACCEPTED','HANGOUT_COMPLETED'].map(eventType=>({label:funnelLabels[eventType]!,value:data.funnel.find(item=>item.eventType===eventType)?._count._all??0})):[];
 const ratingItems=data?[1,2,3,4,5].map(score=>({label:`★${score}`,value:data.ratingDistribution.find(item=>Number(item.score)===score)?._count._all??0})):[];
 const declineItems=data?data.declineReasons.map(item=>({label:reasonLabels[String(item.reason)]??String(item.reason),value:item._count._all})).sort((a,b)=>b.value-a.value):[];
 const feedbackItems=data?data.feedback.map(item=>({label:`${item.algorithmVersion} ${item.outcome==='MATCHED'?'成立':'不成立'}`,value:item._count._all})):[];
 const weightItems=weights?(Object.keys(labels) as Array<keyof Weights>).filter(key=>key!=='baseScore').map(key=>({label:labels[key],value:Math.abs(weights[key])})):[];
 const projectedBest=weights?Math.min(99,Math.round(weights.baseScore+weights.activityMatch+weights.areaMatch+weights.timeMatch+weights.groupMatch+weights.ageMatch+weights.languageMatch+7+3)):0;
 return <main style={{maxWidth:1180,margin:'0 auto',padding:24,fontFamily:'sans-serif',color:'#17221d',background:'#f6f8f6'}}><h1>Hangout Now 運営管理</h1><form onSubmit={load} style={{display:'flex',gap:8,flexWrap:'wrap'}}><input aria-label="管理トークン" type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="管理トークン" required/><input aria-label="担当者ID" value={adminId} onChange={e=>setAdminId(e.target.value)} placeholder="担当者ID" maxLength={100} required/><button>管理データを取得</button></form>{error&&<p role="alert" style={{color:'#a32f20'}}>{error}</p>}
 {data&&<><section style={card}><h2>マッチング状況</h2><p><b>有効バージョン：</b>{data.activeVersion}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{[['登録ユーザー',data.metrics.registeredUsers],['アクティブ・24時間',data.metrics.activeUsers.day],['アクティブ・7日',data.metrics.activeUsers.week],['アクティブ・30日',data.metrics.activeUsers.month],['Hangout',data.metrics.hangouts],['開催完了',data.metrics.completed],['平均評価',data.metrics.averageRating?.toFixed(2)??'—'],['評価件数',data.metrics.ratingCount],['通報',data.metrics.reports]].map(([label,value])=><div key={label} style={{padding:12,background:'#eef4ef',borderRadius:10}}><small>{label}</small><strong style={{display:'block',fontSize:24}}>{value}</strong></div>)}</div><p><small>アクティブユーザーは、対象期間内にログインセッションを作成した重複なしユーザーです。</small></p><h3>バージョン別フィードバック</h3><ul>{data.feedback.map(item=><li key={`${item.algorithmVersion}-${item.outcome}`}>{item.algorithmVersion} / {item.outcome}: {item._count._all}件</li>)}</ul></section>
 <section style={card}><h2>ダウンロード・SNS指標</h2><p>外部サービスの公式APIを接続すると自動集計できます。現在は未連携のため、推測値は表示しません。</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{[['App Store ダウンロード','App Store Connect未連携'],['Google Play ダウンロード','Google Play未連携'],['X 関連投稿','X API未連携'],['Instagram 関連投稿','Instagram Graph API未連携']].map(([label,status])=><div key={label} style={{padding:14,border:'1px solid #e0e6e1',borderRadius:12}}><small>{label}</small><strong style={{display:'block',marginTop:8,fontSize:14,color:'#69736d'}}>{status}</strong></div>)}</div>{push&&<p><b>アプリへ登録済みの端末：</b>{push.registeredTokens}台 <small>（ダウンロード数ではありません）</small></p>}</section>
 <section style={card}><h2>マッチング分析</h2><p>同意済みデータの匿名集計です。個人のトーク本文や正確な位置情報は表示しません。</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:24}}><article><h3>行動ファネル</h3><Bars items={funnelItems}/></article><article><h3>評価分布</h3><Bars items={ratingItems} color="#d09b24"/></article><article><h3>不成立理由</h3>{declineItems.length?<Bars items={declineItems} color="#c4634d"/>:<p>データはまだありません。</p>}</article><article><h3>バージョン別成果</h3>{feedbackItems.length?<Bars items={feedbackItems} color="#426dba"/>:<p>データはまだありません。</p>}</article></div></section>
 <section style={card}><h2>重みの可視化・シミュレーター</h2><p>下の設定値を編集するとグラフと理論上の高一致スコアが即時更新されます。保存するまでは本番へ反映されません。</p><div style={{display:'grid',gridTemplateColumns:'minmax(280px,1fr) minmax(220px,.55fr)',gap:28,alignItems:'start'}}><Bars items={weightItems}/><div style={{padding:20,borderRadius:16,background:'#163f31',color:'#fff',textAlign:'center'}}><small>すべての主要条件が一致した場合</small><strong style={{display:'block',fontSize:50,color:'#d9ff68'}}>{projectedBest}%</strong><span>推定マッチングスコア</span></div></div></section>
 <section style={card}><h2>アルゴリズム設定</h2><p>まず下書きを保存し、内容を確認してから有効化してください。過去バージョンは監査履歴として残ります。</p>{weights&&<form onSubmit={saveDraft}><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><label>新バージョン<input value={version} onChange={e=>setVersion(e.target.value)} pattern="match-v[0-9]+\.[0-9]+\.[0-9]+" required/></label><label style={{flex:1}}>変更理由<input value={note} onChange={e=>setNote(e.target.value)} maxLength={300} required style={{width:'100%'}}/></label></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:16}}>{(Object.keys(labels) as Array<keyof Weights>).map(key=><label key={key}>{labels[key]}<input type="number" value={weights[key]} onChange={e=>setWeights({...weights,[key]:Number(e.target.value)})} style={{display:'block',width:'100%'}} required/></label>)}</div><button style={{marginTop:14}}>下書きを保存</button></form>}<h3>変更履歴</h3>{data.configs.length===0?<p>DB設定はまだありません。現在はコード内の初期値で動作しています。</p>:data.configs.map(config=><article key={config.id} style={{borderTop:'1px solid #ddd',padding:'12px 0'}}><b>{config.version}・{config.status}</b><p>{config.note}<br/><small>作成: {config.createdBy} / {new Date(config.createdAt).toLocaleString('ja-JP')}{config.activatedBy?`　有効化: ${config.activatedBy}`:''}</small></p>{config.status==='DRAFT'&&<button onClick={()=>void activate(config)}>このバージョンを有効化</button>}</article>)}</section></>}
 {push&&<section style={card}><h2>iPhoneプッシュ通知管理</h2><p><b>配信状態：</b>{push.paused?'停止中':'稼働中'}　<b>登録端末：</b>{push.registeredTokens}台</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{push.deliveries.map(item=><div key={item.status} style={{padding:10,background:'#eef4ef',borderRadius:10}}>{item.status}: {item._count._all}件</div>)}</div><div style={{display:'flex',gap:8,marginTop:14}}><button onClick={()=>void pausePush(!push.paused)}>{push.paused?'配信を再開':'緊急停止'}</button><button onClick={()=>void cleanupTokens()}>古い端末トークンを整理</button></div><form onSubmit={sendTestPush} style={{marginTop:16,display:'flex',gap:8,flexWrap:'wrap'}}><input value={testUserId} onChange={e=>setTestUserId(e.target.value)} placeholder="テスト対象ユーザーUUID" required/><button>テスト通知を送信</button></form><p><small>トーク本文はプッシュ通知に含めず、アプリを開いてから表示します。</small></p></section>}
 {data&&<section style={card}><h2>安全管理</h2>{reports.map(report=><article key={report.id} style={{borderTop:'1px solid #ddd',padding:'12px 0'}}><b>{report.reason}・{report.status}</b><p>通報者: {report.reporter.displayName} / 対象: {report.targetUser.displayName}（{report.targetUser.accountStatus}）<br/>{report.hangout?.title??'Hangout指定なし'} / {report.details??'詳細なし'}</p><div style={{display:'flex',gap:8}}><button onClick={()=>void act(report.id,'WARNING')}>警告</button><button onClick={()=>void act(report.id,'SUSPEND')}>一時停止</button><button onClick={()=>void act(report.id,'BAN')}>永久停止</button></div></article>)}</section>}</main>;
}
