"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, ChevronRight, CreditCard, X } from "lucide-react";

type RecordItem={id:string;appointment_id:string;amount_yen:number;status:"pending"|"paid";payment_method:string|null;paid_at:string|null;start_at:string;end_at:string;customer_name:string;product_name:string;therapist_name:string;hal_asset_code:string;started_at:string;ended_at:string;exercise_log:Array<Record<string,unknown>>;soap:Record<string,string>};
type RangeId="day"|"week"|"month"|"year";
type BillingData={records:RecordItem[];summary:{day:number;week:number;month:number;year:number;pending_count:number;pending_amount:number};trend:Array<{label:string;amount:number;count:number}>;periods:Record<RangeId,{start:string;end:string}>;dayPaymentMethods:Array<{payment_method:string;amount:number;count:number}>};
const ranges=[{id:"day",label:"日"},{id:"week",label:"週"},{id:"month",label:"月"},{id:"year",label:"年"}] as const;
const yen=(value:number)=>`¥${value.toLocaleString("ja-JP")}`;
const dt=(value:string)=>new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));
const methodLabel:Record<string,string>={cash:"現金",credit_card:"クレジットカード",qr:"QRコード",ticket:"回数券"};
const methodOrder=["credit_card","cash","qr","ticket"];
const calendarDate=(value:string,withYear=true)=>new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",...(withYear?{year:"numeric" as const}:{}),month:"long",day:"numeric",weekday:"short"}).format(new Date(`${value}T12:00:00+09:00`));
function periodLabel(range:RangeId,period:{start:string;end:string}){if(range==="day")return calendarDate(period.start);if(range==="week")return `${calendarDate(period.start)}〜${calendarDate(period.end,false)}`;const date=new Date(`${period.start}T12:00:00+09:00`);return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",...(range==="month"?{month:"long" as const}:{})}).format(date)}

export function BillingManager(){
 const[data,setData]=useState<BillingData|null>(null);const[range,setRange]=useState<RangeId>("day");const[selected,setSelected]=useState<RecordItem|null>(null);const[method,setMethod]=useState("credit_card");const[confirmed,setConfirmed]=useState(false);const[error,setError]=useState("");const[saving,setSaving]=useState(false);
 async function load(){const r=await fetch("/api/billing",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}
 useEffect(()=>{let active=true;fetch("/api/billing",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);if(active)setData(b)}).catch((e:Error)=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 async function pay(){if(!selected||!confirmed)return;setSaving(true);setError("");try{const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({billingId:selected.id,paymentMethod:method,confirmed:true})});const b=await r.json();if(!r.ok)throw new Error(b.error);setSelected(null);setConfirmed(false);await load()}catch(e){setError(e instanceof Error?e.message:"支払いを確定できませんでした。")}finally{setSaving(false)}}
 if(!data)return <div className="p-8 text-center text-sm">会計データを読み込んでいます…</div>;
 const max=Math.max(...data.trend.map(x=>x.amount),1);const pending=data.records.filter(x=>x.status==="pending"),paid=data.records.filter(x=>x.status==="paid");const dailyMethods=Object.fromEntries(data.dayPaymentMethods.map(item=>[item.payment_method,item]));
 return <div className="mx-auto max-w-[1500px] space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.15em] text-[#087f71]">BILLING</p><h2 className="text-2xl font-black">会計・売上</h2></div><div className="flex rounded-xl bg-white p-1 shadow-sm">{ranges.map(x=><button key={x.id} onClick={()=>setRange(x.id)} className={`rounded-lg px-5 py-2 text-xs font-black ${range===x.id?"bg-[#173b42] text-white":"text-[#71858a]"}`}>{x.label}</button>)}</div></div>
 <div className="rounded-xl border border-[#cfe2de] bg-[#eaf6f3] px-4 py-3"><p className="text-[10px] font-black text-[#087f71]">表示している売上期間</p><p className="mt-0.5 text-lg font-black text-[#173b42]">{periodLabel(range,data.periods[range])}</p></div>
 <div className="grid gap-3 lg:grid-cols-[1.1fr_.9fr]"><section className="grid grid-cols-3 gap-2 rounded-2xl bg-[#173b42] p-4 text-white"><div><p className="text-[10px] text-white/55">{ranges.find(x=>x.id===range)?.label}の売上・全ての合計</p><p className="mt-1 text-3xl font-black">{yen(data.summary[range])}</p></div><div><p className="text-[10px] text-white/55">会計待ち</p><p className="mt-1 text-2xl font-black text-[#ffd987]">{data.summary.pending_count}件</p></div><div><p className="text-[10px] text-white/55">未収金額</p><p className="mt-1 text-2xl font-black">{yen(data.summary.pending_amount)}</p></div></section><section className="flex h-[92px] items-end gap-2 rounded-2xl border border-[#dce8e5] bg-white px-4 pb-3 pt-2">{data.trend.map(x=><div key={x.label} className="flex flex-1 flex-col items-center justify-end"><div title={`${x.label} ${yen(x.amount)}`} className="w-full rounded-t bg-[#65bcae]" style={{height:`${Math.max(6,x.amount/max*48)}px`}}/><span className="mt-1 text-[9px] text-[#71858a]">{Number(x.label.slice(5))}月</span></div>)}</section></div>
 {range==="day"&&<section className="rounded-2xl border border-[#dce8e5] bg-white p-3"><h3 className="text-sm font-black">本日の支払い方法別売上</h3><div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-5"><div className="rounded-xl bg-[#173b42] p-3 text-white"><p className="text-[10px] text-white/60">全ての合計</p><p className="mt-1 text-xl font-black">{yen(data.summary.day)}</p></div>{methodOrder.map(key=><div key={key} className="rounded-xl bg-[#f3f7f6] p-3"><p className="text-[10px] font-bold text-[#71858a]">{methodLabel[key]}の合計</p><p className="mt-1 text-xl font-black text-[#173b42]">{yen(Number(dailyMethods[key]?.amount??0))}</p><p className="mt-1 text-[10px] text-[#819397]">{Number(dailyMethods[key]?.count??0)}件</p></div>)}</div></section>}
 {error&&<p role="alert" className="rounded-xl bg-[#fff0ed] p-3 text-sm font-bold text-[#b94637]">{error}</p>}
 <div className="grid min-h-0 gap-3 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-[#dce8e5] bg-white p-3"><div className="mb-2 flex items-center justify-between"><h3 className="font-black">施術終了・会計待ち</h3><span className="rounded-full bg-[#fff3d5] px-3 py-1 text-xs font-black text-[#9a6810]">{pending.length}件</span></div><div className="space-y-2">{pending.map(x=><button key={x.id} onClick={()=>{setSelected(x);setConfirmed(false)}} className="grid w-full grid-cols-[1fr_auto] items-center gap-3 rounded-xl border border-[#dce8e5] p-3 text-left hover:border-[#69b9aa]"><div><p className="font-black">{x.customer_name} <span className="ml-2 text-xs font-normal text-[#71858a]">{dt(x.ended_at)} 終了</span></p><p className="mt-1 text-xs text-[#71858a]">{x.product_name}・{x.therapist_name}・{x.hal_asset_code}</p></div><div className="flex items-center gap-2"><b>{yen(x.amount_yen)}</b><ChevronRight size={17}/></div></button>)}{pending.length===0&&<p className="p-5 text-center text-sm text-[#71858a]">会計待ちはありません。</p>}</div></section>
 <section className="rounded-2xl border border-[#dce8e5] bg-white p-3"><div className="mb-2 flex items-center justify-between"><h3 className="font-black">支払い済み</h3><CheckCircle2 size={19} className="text-[#087f71]"/></div><div className="max-h-[320px] space-y-2 overflow-auto">{paid.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-[#f3f7f6] p-3"><div><p className="text-sm font-black">{x.customer_name}・{x.product_name}</p><p className="mt-1 text-[10px] text-[#71858a]">{dt(x.paid_at!)}・{methodLabel[x.payment_method||""]}</p></div><b className="text-[#087f71]">{yen(x.amount_yen)}</b></div>)}</div></section></div>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#09262c]/55 p-3"><section role="dialog" aria-label="支払い確認" className="w-full max-w-2xl rounded-3xl bg-white p-5"><div className="flex justify-between"><div><p className="text-[10px] font-black text-[#087f71]">TREATMENT & PAYMENT</p><h3 className="text-xl font-black">施術内容と支払い確認</h3></div><button aria-label="閉じる" onClick={()=>setSelected(null)}><X/></button></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Info label="利用者" value={selected.customer_name}/><Info label="請求額" value={yen(selected.amount_yen)}/><Info label="実施施術" value={selected.product_name}/><Info label="実施時間" value={`${dt(selected.started_at)}〜${dt(selected.ended_at)}`}/><Info label="担当・機器" value={`${selected.therapist_name}・${selected.hal_asset_code}`}/><Info label="運動記録" value={selected.exercise_log.map(x=>String(x.exercise||"HALトレーニング")).join("、")}/></div><label className="mt-4 block text-xs font-bold">支払い方法<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-2 w-full rounded-xl border p-3 text-sm"><option value="credit_card">クレジットカード</option><option value="cash">現金</option><option value="qr">QRコード</option><option value="ticket">回数券</option></select></label><label className="mt-4 flex items-center gap-3 rounded-xl bg-[#fff7df] p-3 text-sm font-bold"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="size-5"/>施術内容・請求額・入金を確認しました</label><button disabled={!confirmed||saving} onClick={pay} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#087f71] py-3.5 font-black text-white disabled:bg-[#a9c3be]"><CreditCard size={18}/>{saving?"確定中…":"支払い済みにする"}</button></section></div>}</div>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f3f7f6] p-3"><p className="text-[10px] text-[#71858a]">{label}</p><p className="mt-1 font-black">{value}</p></div>}
