import { BadRequestException, ConflictException, ForbiddenException, Inject, Injectable, NotFoundException, OnModuleDestroy, OnModuleInit, Optional } from '@nestjs/common';
import { AttendanceStatus, Gender, GenderRestriction, HangoutStatus, JoinRequestStatus, Prisma, ServiceArea } from '@prisma/client';
import { v7 as uuidv7 } from 'uuid';
import { PrismaService } from '../prisma/prisma.service';
import { CreateHangoutDto, JoinHangoutDto, RateParticipantDto, UpdateAttendanceDto, UpdateHangoutDto } from './hangout.dto';
import { NotificationService } from '../notifications/notification.service';
import { HostStatus, HostStatusService } from '../host-status/host-status.service';
import { MatchingService } from '../matching/matching.service';
import { HANGOUT_IMAGE_SPEC, optimizeDataImage } from '../storage/image-optimization';
import { HangoutDetailDto, HangoutListItemDto } from './hangout-response.dto';

const hangoutListSelect = (userId: string) => ({
  id: true,
  hostUserId: true,
  status: true,
  title: true,
  imageUrl: true,
  category: true,
  serviceArea: true,
  startAt: true,
  publicLocationName: true,
  publicLatitude: true,
  publicLongitude: true,
  maxParticipants: true,
  hostMaleCount: true,
  hostFemaleCount: true,
  genderRestriction: true,
  maxAge: true,
  host: { select: { id: true, displayName: true, verification: true, profilePhoto: true, gender: true, birthDate: true, socialStyles: true, preferredLanguages: true } },
  joinRequests: { where: { OR: [{ status: JoinRequestStatus.ACCEPTED }, { userId }] }, select: { id: true, userId: true, status: true } },
  hearts: { where: { userId }, select: { userId: true } },
  _count: { select: { hearts: true } },
}) satisfies Prisma.HangoutSelect;

const hangoutDetailInclude = (userId: string) => ({
  host: { select: { id: true, displayName: true, verification: true, profilePhoto: true, profilePhotos: true, gender: true, birthDate: true, socialStyles: true, preferredLanguages: true } },
  joinRequests: {
    where: { OR: [{ status: JoinRequestStatus.ACCEPTED }, { userId }] },
    select: {
      id: true,
      userId: true,
      status: true,
      attendanceStatus: true,
      user: { select: { id: true, displayName: true, verification: true, profilePhoto: true, profilePhotos: true, gender: true, birthDate: true, bio: true, homeArea: true, interests: { select: { interest: { select: { name: true } } } } } },
    },
  },
  hearts: { where: { userId }, select: { userId: true } },
  _count: { select: { hearts: true } },
}) satisfies Prisma.HangoutInclude;

type HangoutListRow = Prisma.HangoutGetPayload<{ select: ReturnType<typeof hangoutListSelect> }>;
type HangoutDetailRow = Prisma.HangoutGetPayload<{ include: ReturnType<typeof hangoutDetailInclude> }>;

@Injectable()
export class HangoutService implements OnModuleInit, OnModuleDestroy {
 private lifecycleTimer?: NodeJS.Timeout;
 constructor(@Inject(PrismaService)private readonly db:PrismaService,@Inject(NotificationService)private readonly notifications:NotificationService,@Inject(HostStatusService)private readonly hostStatuses:HostStatusService,@Optional()@Inject(MatchingService)private readonly matching?:MatchingService){}
 onModuleInit(){this.lifecycleTimer=setInterval(()=>void this.reconcileDueHangouts().catch(()=>undefined),15_000);void this.reconcileDueHangouts().catch(()=>undefined)}
 onModuleDestroy(){if(this.lifecycleTimer)clearInterval(this.lifecycleTimer)}
 async create(uid:string,x:CreateHangoutDto):Promise<HangoutDetailDto>{const user=await this.db.user.findUnique({where:{id:uid},select:{profilePhoto:true,gender:true,email:true}});if(!user?.profilePhoto)throw new ForbiddenException('Profile photo is required to create a Hangout');this.validateAreaCoordinates(x.serviceArea,x.latitude,x.longitude);const hostMaleCount=user.gender===Gender.FEMALE?0:1;const hostFemaleCount=user.gender===Gender.FEMALE?1:0;const imageUrl=await this.normalizeHangoutImage(x.imageUrl);const row=await this.db.hangout.create({data:{id:uuidv7(),hostUserId:uid,title:x.title.trim(),description:x.description?.trim(),imageUrl,category:x.category,serviceArea:x.serviceArea,startAt:new Date(Date.now()+x.startInMinutes*60000),locationName:x.locationName.trim(),meetingPlaceName:x.meetingPlaceName?.trim(),meetingAddress:x.meetingAddress?.trim(),navigationUrl:x.navigationUrl?.trim(),publicLocationName:x.publicLocationName.trim(),latitude:x.latitude,longitude:x.longitude,publicLatitude:x.latitude==null?null:Math.round(x.latitude*100)/100,publicLongitude:x.longitude==null?null:Math.round(x.longitude*100)/100,maxParticipants:x.maxParticipants,hostMaleCount,hostFemaleCount,genderRestriction:x.genderRestriction??GenderRestriction.ANY,maxAge:x.maxAge,isDemo:user.email.endsWith('@hangoutnow.example')}});return this.get(uid,row.id)}
 async list(uid:string,time?:string,latitude?:string,longitude?:string,radiusKm?:string):Promise<HangoutListItemDto[]>{const m=time?Number(time):0;const hasPosition=latitude!==undefined||longitude!==undefined;if(hasPosition&&(latitude===undefined||longitude===undefined))throw new BadRequestException('Latitude and longitude must be provided together');const lat=latitude===undefined?undefined:Number(latitude);const lng=longitude===undefined?undefined:Number(longitude);const radius=radiusKm===undefined?20:Number(radiusKm);if(lat!==undefined&&(!Number.isFinite(lat)||lat < -90||lat > 90||!Number.isFinite(lng)||lng! < -180||lng! > 180))throw new BadRequestException('Invalid coordinates');if(!Number.isFinite(radius)||radius<1||radius>50)throw new BadRequestException('radiusKm must be between 1 and 50');const [blocks,viewer]=await Promise.all([this.db.block.findMany({where:{OR:[{blockerId:uid},{blockedId:uid}]}}),this.db.user.findUnique({where:{id:uid},select:{email:true}})]);if(!viewer)throw new NotFoundException();const hidden=blocks.map(b=>b.blockerId===uid?b.blockedId:b.blockerId);const demoViewer=viewer.email.endsWith('@hangoutnow.example');const rows=await this.db.hangout.findMany({where:{hostUserId:{notIn:hidden},...(demoViewer?{}:{isDemo:false}),status:{in:[HangoutStatus.OPEN,HangoutStatus.FULL,HangoutStatus.STARTED]},...([30,60,180].includes(m)?{startAt:{lte:new Date(Date.now()+m*60000+90000)}}:{})},orderBy:{startAt:'asc'},select:hangoutListSelect(uid)});const [statuses,scores]=await Promise.all([this.hostStatuses.forUsers(rows.map(r=>r.hostUserId)),this.matching?this.matching.scoresFor(uid,rows):Promise.resolve(new Map<string,number>())]);return rows.map(r=>this.toListItem(r,statuses.get(r.hostUserId),scores.get(r.id)??70,uid,lat,lng)).filter(r=>r.distanceKm===null||r.distanceKm<=radius).sort((a,b)=>b.matchScore-a.matchScore||(lat===undefined?a.startAt.getTime()-b.startAt.getTime():(a.distanceKm??Infinity)-(b.distanceKm??Infinity)))}
 async activity(uid:string){const rows=await this.db.hangout.findMany({where:{OR:[{hostUserId:uid},{joinRequests:{some:{userId:uid,status:JoinRequestStatus.ACCEPTED}}},{hearts:{some:{userId:uid}}}]},select:{id:true,title:true,status:true,startAt:true,imageUrl:true,category:true,publicLocationName:true,hostUserId:true,hearts:{where:{userId:uid},select:{userId:true}},joinRequests:{where:{userId:uid,status:JoinRequestStatus.ACCEPTED},select:{id:true}}},orderBy:{startAt:'desc'},take:60});const item=(row:typeof rows[number])=>({id:row.id,title:row.title,status:row.status,startAt:row.startAt,imageUrl:row.imageUrl,category:row.category,publicLocationName:row.publicLocationName});return{hosted:rows.filter(row=>row.hostUserId===uid&&row.status!==HangoutStatus.CANCELLED).map(item),participated:rows.filter(row=>row.hostUserId!==uid&&row.joinRequests.length>0).map(item),hearted:rows.filter(row=>row.hearts.length>0).map(item)}}
 async get(uid:string,id:string):Promise<HangoutDetailDto>{const r=await this.db.hangout.findUnique({where:{id},include:hangoutDetailInclude(uid)});if(!r)throw new NotFoundException();const [status,scores]=await Promise.all([this.hostStatuses.forUser(r.hostUserId),this.matching?this.matching.scoresFor(uid,[r]):Promise.resolve(new Map<string,number>())]);return this.toDetail(r,status,scores.get(r.id)??70,uid)}
 async toggleHeart(uid:string,id:string){if(!await this.db.hangout.findUnique({where:{id},select:{id:true}}))throw new NotFoundException();const key={hangoutId_userId:{hangoutId:id,userId:uid}};const current=await this.db.hangoutHeart.findUnique({where:key});if(current)await this.db.hangoutHeart.delete({where:key});else await this.db.hangoutHeart.create({data:{hangoutId:id,userId:uid}});return{hearted:!current,heartCount:await this.db.hangoutHeart.count({where:{hangoutId:id}})}}
 async update(uid:string,id:string,x:UpdateHangoutDto){await this.host(uid,id);const changes={...x};delete changes.hostMaleCount;delete changes.hostFemaleCount;const imageUrl=await this.normalizeHangoutImage(x.imageUrl);return this.db.hangout.update({where:{id},data:{...changes,...(imageUrl===undefined?{}:{imageUrl})}})}
 async cancel(uid:string,id:string){await this.host(uid,id);await this.db.hangout.delete({where:{id}})}
 async start(uid:string,id:string){const h=await this.hangoutForTransition(uid,id);if(h.status!==HangoutStatus.OPEN&&h.status!==HangoutStatus.FULL)throw new ConflictException('Hangout cannot be started');if(!h.joinRequests.length)throw new ConflictException('参加メンバーがいないためHangoutを開始できません');return this.transitionWithTalkNotice(h,HangoutStatus.STARTED,'Hangout開始')}
 async finish(uid:string,id:string){const h=await this.hangoutForTransition(uid,id);if(h.status!==HangoutStatus.STARTED)throw new ConflictException('Hangout must be started before it can be finished');return this.transitionWithTalkNotice(h,HangoutStatus.FINISHED,'Hangout終了')}
 async rate(uid:string,id:string,x:RateParticipantDto){const h=await this.db.hangout.findUnique({where:{id},include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED}}}});if(!h)throw new NotFoundException();if(h.status!==HangoutStatus.FINISHED)throw new ConflictException('Hangout must be finished before rating');const memberIds=new Set([h.hostUserId,...h.joinRequests.map(r=>r.userId)]);if(!memberIds.has(uid)||!memberIds.has(x.ratedUserId))throw new ForbiddenException('Only participants can rate each other');if(uid===x.ratedUserId)throw new BadRequestException('You cannot rate yourself');const key={hangoutId_raterUserId_ratedUserId:{hangoutId:id,raterUserId:uid,ratedUserId:x.ratedUserId}};if(await this.db.hangoutRating.findUnique({where:key}))throw new ConflictException('Rating has already been submitted');try{return await this.db.hangoutRating.create({data:{id:uuidv7(),hangoutId:id,raterUserId:uid,ratedUserId:x.ratedUserId,score:x.score}})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('Rating has already been submitted');throw error}}
 // @ts-expect-error Array inference narrows the accepted enum members; runtime values are validated above.
 async join(uid:string,id:string,x:JoinHangoutDto){const h=await this.db.hangout.findUnique({where:{id},include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED}}}});if(!h)throw new NotFoundException();const user=await this.db.user.findUnique({where:{id:uid},select:{birthDate:true,gender:true,displayName:true}});if(!user)throw new NotFoundException();if(h.genderRestriction!==GenderRestriction.ANY){const required=h.genderRestriction===GenderRestriction.MALE_ONLY?Gender.MALE:Gender.FEMALE;if(user.gender!==required)throw new ForbiddenException('このHangoutの性別条件を満たしていません')}if(h.maxAge!==null&&this.age(user.birthDate)>h.maxAge)throw new ForbiddenException('このHangoutの年齢条件を満たしていません');if(await this.db.block.findFirst({where:{OR:[{blockerId:uid,blockedId:h.hostUserId},{blockerId:h.hostUserId,blockedId:uid}]}}))throw new ForbiddenException('Blocked relationship');if(h.hostUserId===uid)throw new BadRequestException('Host cannot join own Hangout');if(![HangoutStatus.OPEN,HangoutStatus.FULL,HangoutStatus.STARTED].includes(h.status))throw new ConflictException('Hangout is not accepting requests');const hostCount=h.hostMaleCount+h.hostFemaleCount;const waitlisted=h.status===HangoutStatus.FULL||hostCount+h.joinRequests.length>=h.maxParticipants;const existing=(await this.db.joinRequest.findMany({where:{hangoutId:id}})).find(request=>request.userId===uid);if(existing&&[JoinRequestStatus.PENDING,JoinRequestStatus.ACCEPTED,JoinRequestStatus.WAITLISTED].includes(existing.status))throw new ConflictException('Join request already exists');const data={message:x.message,status:waitlisted?JoinRequestStatus.WAITLISTED:JoinRequestStatus.PENDING,attendanceStatus:null,attendanceUpdatedAt:null};let out;try{out=existing?await this.db.joinRequest.update({where:{id:existing.id},data}):await this.db.joinRequest.create({data:{id:uuidv7(),hangoutId:id,userId:uid,...data}})}catch{throw new ConflictException('Join request already exists')}try{if(waitlisted)await this.notifications.notify(uid,'WAITLISTED','待機リストに登録しました',`「${h.title}」に空きが出たらお知らせします。`,`hangout:${id}`,`waitlisted:${out.id}`);else await this.notifications.notify(h.hostUserId,'JOIN_REQUEST','参加申請が届きました',`${user.displayName}さんが「${h.title}」への参加を希望しています。`,`hangout:${id}`,`join:${out.id}`)}catch{/* The saved join request remains authoritative when notification delivery fails. */}return out}
 async requests(uid:string,id:string){await this.host(uid,id);const rows=await this.db.joinRequest.findMany({where:{hangoutId:id},include:{user:{select:{id:true,displayName:true,verification:true,profilePhoto:true,profilePhotos:true,birthDate:true,bio:true,homeArea:true,interests:{select:{interest:{select:{name:true}}}}}}}});return rows.map(row=>({...row,user:{id:row.user.id,displayName:row.user.displayName,verification:row.user.verification,profilePhoto:row.user.profilePhoto,profilePhotos:row.user.profilePhotos,age:row.user.birthDate?this.age(row.user.birthDate):null,bio:row.user.bio,homeArea:row.user.homeArea,interests:row.user.interests.map(item=>item.interest.name)}}))}
 async decide(uid:string,rid:string,accept:boolean){const initial=await this.db.joinRequest.findUnique({where:{id:rid},include:{hangout:{include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED}}}}}});if(!initial)throw new NotFoundException();if(initial.hangout.hostUserId!==uid)throw new ForbiddenException();if(initial.status!==JoinRequestStatus.PENDING)throw new ConflictException('Already decided');const out=await this.db.$transaction(async tx=>{if(accept&&typeof tx.$executeRawUnsafe==='function')await tx.$executeRawUnsafe('SELECT pg_advisory_xact_lock(hashtext($1))',initial.hangoutId);const current=await tx.joinRequest.findUnique({where:{id:rid},include:{hangout:{include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED}}}}}});if(!current||current.status!==JoinRequestStatus.PENDING)throw new ConflictException('Already decided');const hostCount=current.hangout.hostMaleCount+current.hangout.hostFemaleCount;if(accept&&hostCount+current.hangout.joinRequests.length>=current.hangout.maxParticipants)throw new ConflictException('Hangout is full');const result=await tx.joinRequest.update({where:{id:rid},data:{status:accept?JoinRequestStatus.ACCEPTED:JoinRequestStatus.REJECTED,attendanceStatus:accept?AttendanceStatus.PENDING_CONFIRMATION:null,attendanceUpdatedAt:accept?new Date():null}});if(accept){await tx.chatRoom.upsert({where:{hangoutId:current.hangoutId},create:{id:uuidv7(),hangoutId:current.hangoutId},update:{}});if(hostCount+current.hangout.joinRequests.length+1>=current.hangout.maxParticipants)await tx.hangout.update({where:{id:current.hangoutId},data:{status:HangoutStatus.FULL}})}return result});await this.notifications.notify(initial.userId,accept?'JOIN_ACCEPTED':'JOIN_REJECTED',accept?'参加が承認されました':'参加申請の結果',`「${initial.hangout.title}」の参加申請が${accept?'承認':'見送り'}となりました。`,`hangout:${initial.hangoutId}`,`decision:${rid}`);await this.reconcileDueHangout(initial.hangoutId);return out}
 async updateAttendance(uid:string,rid:string,x:UpdateAttendanceDto){const initial=await this.db.joinRequest.findUnique({where:{id:rid},include:{hangout:true}});if(!initial)throw new NotFoundException();if(initial.userId!==uid)throw new ForbiddenException();if(initial.status!==JoinRequestStatus.ACCEPTED)throw new ConflictException('Only accepted participants can update attendance');if(initial.hangout.status===HangoutStatus.STARTED||initial.hangout.status===HangoutStatus.FINISHED||initial.hangout.status===HangoutStatus.CANCELLED)throw new ConflictException('Attendance can no longer be changed');if(x.status===AttendanceStatus.CONFIRMED)return this.db.joinRequest.update({where:{id:rid},data:{attendanceStatus:x.status,attendanceUpdatedAt:new Date()}});const result=await this.db.$transaction(async tx=>{if(typeof tx.$executeRawUnsafe==='function')await tx.$executeRawUnsafe('SELECT pg_advisory_xact_lock(hashtext($1))',initial.hangoutId);const current=await tx.joinRequest.findUnique({where:{id:rid}});if(!current||current.status!==JoinRequestStatus.ACCEPTED)throw new ConflictException('Attendance already changed');const cancelled=await tx.joinRequest.update({where:{id:rid},data:{status:JoinRequestStatus.CANCELLED,attendanceStatus:AttendanceStatus.CANCELLED,attendanceUpdatedAt:new Date()}});await tx.hangout.update({where:{id:initial.hangoutId},data:{status:HangoutStatus.OPEN}});return cancelled});const next=await this.db.joinRequest.findFirst({where:{hangoutId:initial.hangoutId,status:JoinRequestStatus.WAITLISTED},orderBy:{createdAt:'asc'}});if(next)await this.notifications.notify(next.userId,'WAITLIST_OPEN','空きが出ました',`「${initial.hangout.title}」に空きが出ました。参加する場合は募集画面から再申請してください。`,`hangout:${initial.hangoutId}`,`waitlist-open:${rid}:${next.id}`);await this.notifications.notify(initial.hangout.hostUserId,'ATTENDANCE_CANCELLED','参加者がキャンセルしました',`「${initial.hangout.title}」の参加枠が1つ空きました。`,`hangout:${initial.hangoutId}`,`attendance-cancelled:${rid}`);return result}
 private validateAreaCoordinates(area:ServiceArea,latitude?:number,longitude?:number){if(latitude===undefined&&longitude===undefined)return;if(latitude===undefined||longitude===undefined)throw new BadRequestException('Latitude and longitude must be provided together');const bounds=area===ServiceArea.SHINJUKU?{minLat:35.66,maxLat:35.73,minLng:139.67,maxLng:139.74}:{minLat:35.63,maxLat:35.70,minLng:139.67,maxLng:139.73};if(latitude<bounds.minLat||latitude>bounds.maxLat||longitude<bounds.minLng||longitude>bounds.maxLng)throw new BadRequestException('Coordinates must be within the selected service area')}
 private async normalizeHangoutImage(value?:string|null){if(value===undefined||value===null)return value;if(/^https:\/\/(?:method-more\.com|hangoutnow-demo\.onrender\.com)\/assets\/[A-Za-z0-9._-]+\.(?:jpe?g|png|webp)$/.test(value))return value;return(await optimizeDataImage(value,HANGOUT_IMAGE_SPEC)).dataUrl}
 private async host(uid:string,id:string){const h=await this.db.hangout.findUnique({where:{id}});if(!h)throw new NotFoundException();if(h.hostUserId!==uid)throw new ForbiddenException();return h}
 private async hangoutForTransition(uid:string,id:string){const h=await this.db.hangout.findUnique({where:{id},include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED},select:{userId:true}}}});if(!h)throw new NotFoundException();if(h.hostUserId!==uid)throw new ForbiddenException();return h}
 private async transitionWithTalkNotice(h:{id:string;hostUserId:string;joinRequests:Array<{userId:string}>},status:HangoutStatus,body:string){const messageId=uuidv7();const transitionTime=new Date();const result=await this.db.$transaction(async tx=>{const room=await tx.chatRoom.upsert({where:{hangoutId:h.id},create:{id:uuidv7(),hangoutId:h.id},update:{}});const hangout=await tx.hangout.update({where:{id:h.id},data:{status,...(status===HangoutStatus.STARTED?{startedAt:transitionTime}:{}),...(status===HangoutStatus.FINISHED?{endedAt:transitionTime}:{})}});await tx.message.create({data:{id:messageId,roomId:room.id,senderUserId:h.hostUserId,body}});return{hangout,roomId:room.id}});for(const request of h.joinRequests)await this.notifications.notify(request.userId,'CHAT_MESSAGE',body,body,`group-chat:${result.roomId}`,`message:${messageId}:${request.userId}`);return result.hangout}
 async reconcileDueHangouts(now=new Date()){const expirationCutoff=new Date(now.getTime()-3*60*60*1000);const [due,expired]=await Promise.all([this.db.hangout.findMany({where:{startAt:{lte:now},status:{in:[HangoutStatus.OPEN,HangoutStatus.FULL]}},select:{id:true},take:100}),this.db.hangout.findMany({where:{status:HangoutStatus.STARTED,OR:[{startedAt:{lte:expirationCutoff}},{startedAt:null,startAt:{lte:expirationCutoff}}]},select:{id:true},take:100})]);for(const row of due)await this.reconcileDueHangout(row.id,now);for(const row of expired)await this.finishExpiredHangout(row.id,now)}
 private async finishExpiredHangout(id:string,now=new Date()){const hangout=await this.db.hangout.findUnique({where:{id},include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED},select:{userId:true}}}});const startedAt=hangout?.startedAt??hangout?.startAt;if(!hangout||hangout.status!==HangoutStatus.STARTED||!startedAt||startedAt.getTime()>now.getTime()-3*60*60*1000)return;const changed=await this.db.hangout.updateMany({where:{id,status:HangoutStatus.STARTED},data:{status:HangoutStatus.FINISHED,endedAt:now}});if(!changed.count)return;const body='Hangoutは開始から3時間が経過したため終了しました';const messageId=uuidv7();const room=await this.db.chatRoom.upsert({where:{hangoutId:id},create:{id:uuidv7(),hangoutId:id},update:{}});await this.db.message.create({data:{id:messageId,roomId:room.id,senderUserId:hangout.hostUserId,body}});await this.notifications.notify(hangout.hostUserId,'HANGOUT_FINISHED','Hangoutを終了しました',`「${hangout.title}」は開始から3時間が経過したため終了しました。`,`hangout:${id}`,`auto-finished-max-duration:${id}`);for(const request of hangout.joinRequests)await this.notifications.notify(request.userId,'CHAT_MESSAGE',body,body,`group-chat:${room.id}`,`message:${messageId}:${request.userId}`)}
 private async reconcileDueHangout(id:string,now=new Date()){const hangout=await this.db.hangout.findUnique({where:{id},include:{joinRequests:{where:{status:{in:[JoinRequestStatus.PENDING,JoinRequestStatus.ACCEPTED]}},select:{userId:true,status:true}}}});if(!hangout||hangout.startAt>now||(hangout.status!==HangoutStatus.OPEN&&hangout.status!==HangoutStatus.FULL))return;const accepted=hangout.joinRequests.filter(request=>request.status===JoinRequestStatus.ACCEPTED);if(accepted.length){await this.transitionWithTalkNotice({...hangout,joinRequests:accepted},HangoutStatus.STARTED,'Hangout開始');return}if(hangout.joinRequests.some(request=>request.status===JoinRequestStatus.PENDING))return;const changed=await this.db.hangout.updateMany({where:{id,status:{in:[HangoutStatus.OPEN,HangoutStatus.FULL]}},data:{status:HangoutStatus.FINISHED}});if(changed.count)await this.notifications.notify(hangout.hostUserId,'HANGOUT_FINISHED','Hangoutを終了しました',`「${hangout.title}」は開始時刻までに参加者がいなかったため終了しました。`,`hangout:${id}`,`auto-finished:${id}`)}
 private toListItem(row:HangoutListRow,hostStatus:HostStatus|undefined,matchScore:number,userId:string,viewerLat?:number,viewerLng?:number):HangoutListItemDto{
  if(!hostStatus)throw new Error(`Host status not found for ${row.hostUserId}`);
  const distanceKm=viewerLat===undefined||viewerLng===undefined||row.publicLatitude===null||row.publicLongitude===null?null:this.distance(viewerLat,viewerLng,row.publicLatitude,row.publicLongitude);
  const acceptedCount=row.joinRequests.filter(request=>request.status===JoinRequestStatus.ACCEPTED).length;
  const myJoinStatus=row.joinRequests.find(request=>request.userId===userId)?.status??null;
  return{id:row.id,hostUserId:row.hostUserId,status:row.status,title:row.title,imageUrl:row.imageUrl,category:row.category,serviceArea:row.serviceArea,startAt:row.startAt,locationName:row.publicLocationName,publicLocationName:row.publicLocationName,distanceKm,participantCount:row.hostMaleCount+row.hostFemaleCount+acceptedCount,maxParticipants:row.maxParticipants,genderRestriction:row.genderRestriction,maxAge:row.maxAge,myJoinStatus,host:{id:row.host.id,displayName:row.host.displayName,verification:row.host.verification,profilePhoto:row.host.profilePhoto,hostStatus},hearted:(row.hearts?.length??0)>0,heartCount:row._count?.hearts??0,matchScore}
 }
 private toDetail(row:HangoutDetailRow,hostStatus:HostStatus,matchScore:number,userId:string):HangoutDetailDto{
  const accepted=row.joinRequests.filter(request=>request.status===JoinRequestStatus.ACCEPTED);
  const exact=row.hostUserId===userId||accepted.some(request=>request.userId===userId);
  const mine=row.joinRequests.find(request=>request.userId===userId);
  return{id:row.id,hostUserId:row.hostUserId,status:row.status,title:row.title,description:row.description??null,imageUrl:row.imageUrl??null,category:row.category,serviceArea:row.serviceArea,startAt:row.startAt,locationName:exact?row.locationName:row.publicLocationName,publicLocationName:row.publicLocationName,meetingPlaceName:exact?row.meetingPlaceName:undefined,meetingAddress:exact?row.meetingAddress:undefined,navigationUrl:exact?row.navigationUrl:undefined,latitude:exact?row.latitude??undefined:undefined,longitude:exact?row.longitude??undefined:undefined,publicLatitude:row.publicLatitude,publicLongitude:row.publicLongitude,locationPrecision:exact?'EXACT':'APPROXIMATE',distanceKm:null,participantCount:row.hostMaleCount+row.hostFemaleCount+accepted.length,hostParticipantCount:row.hostMaleCount+row.hostFemaleCount,maxParticipants:row.maxParticipants,hostMaleCount:row.hostMaleCount,hostFemaleCount:row.hostFemaleCount,genderRestriction:row.genderRestriction,maxAge:row.maxAge,isDemo:row.isDemo,host:{id:row.host.id,displayName:row.host.displayName,verification:row.host.verification,profilePhoto:row.host.profilePhoto,profilePhotos:row.host.profilePhotos??[],hostStatus},acceptedParticipants:accepted.map(request=>({id:request.user.id,displayName:request.user.displayName,verification:request.user.verification,profilePhoto:request.user.profilePhoto,profilePhotos:request.user.profilePhotos??[],gender:request.user.gender,age:request.user.birthDate?this.age(request.user.birthDate):undefined,bio:request.user.bio,homeArea:request.user.homeArea,interests:request.user.interests.map(item=>item.interest.name)})),myJoinStatus:mine?.status??null,myJoinRequestId:mine?.id??null,myAttendanceStatus:mine?.attendanceStatus??null,hearted:(row.hearts?.length??0)>0,heartCount:row._count?.hearts??0,matchScore}
 }
 private age(birthDate:Date|null){if(!birthDate)return Number.MAX_SAFE_INTEGER;const today=new Date();let age=today.getUTCFullYear()-birthDate.getUTCFullYear();if(today.getUTCMonth()<birthDate.getUTCMonth()||(today.getUTCMonth()===birthDate.getUTCMonth()&&today.getUTCDate()<birthDate.getUTCDate()))age-=1;return age}
 private distance(lat1:number,lng1:number,lat2:number,lng2:number){const rad=(n:number)=>n*Math.PI/180;const a=Math.sin(rad(lat2-lat1)/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(rad(lng2-lng1)/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))*10)/10}
}
