import { BadRequestException, ConflictException, ForbiddenException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { Gender, GenderRestriction, HangoutStatus, JoinRequestStatus } from '@prisma/client';
import { v7 as uuidv7 } from 'uuid';
import { PrismaService } from '../prisma/prisma.service';
import { CreateHangoutDto, JoinHangoutDto, RateParticipantDto, UpdateHangoutDto } from './hangout.dto';
import { NotificationService } from '../notifications/notification.service';
import { HostStatusService } from '../host-status/host-status.service';
@Injectable()
export class HangoutService {
 constructor(@Inject(PrismaService)private readonly db:PrismaService,@Inject(NotificationService)private readonly notifications:NotificationService,@Inject(HostStatusService)private readonly hostStatuses:HostStatusService){}
 async create(uid:string,x:CreateHangoutDto){const user=await this.db.user.findUnique({where:{id:uid},select:{verification:true,profilePhoto:true}});if(!user?.profilePhoto)throw new ForbiddenException('Profile photo is required to create a Hangout');if(user.verification!=='PHONE_VERIFIED')throw new ForbiddenException('Phone verification is required to create a Hangout');const row=await this.db.hangout.create({data:{id:uuidv7(),hostUserId:uid,title:x.title.trim(),description:x.description?.trim(),category:x.category,startAt:new Date(Date.now()+x.startInMinutes*60000),locationName:x.locationName.trim(),latitude:x.latitude,longitude:x.longitude,publicLatitude:x.latitude==null?null:Math.round(x.latitude*100)/100,publicLongitude:x.longitude==null?null:Math.round(x.longitude*100)/100,maxParticipants:x.maxParticipants,genderRestriction:x.genderRestriction??GenderRestriction.ANY,maxAge:x.maxAge},include:this.inc(uid)});const status=await this.hostStatuses.forUser(uid);return this.show({...row,host:{...row.host,hostStatus:status}},uid)}
 async list(uid:string,time?:string,latitude?:string,longitude?:string,radiusKm?:string){const m=time?Number(time):0;const hasPosition=latitude!==undefined||longitude!==undefined;if(hasPosition&&(latitude===undefined||longitude===undefined))throw new BadRequestException('Latitude and longitude must be provided together');const lat=latitude===undefined?undefined:Number(latitude);const lng=longitude===undefined?undefined:Number(longitude);const radius=radiusKm===undefined?20:Number(radiusKm);if(lat!==undefined&&(!Number.isFinite(lat)||lat < -90||lat > 90||!Number.isFinite(lng)||lng! < -180||lng! > 180))throw new BadRequestException('Invalid coordinates');if(!Number.isFinite(radius)||radius<1||radius>50)throw new BadRequestException('radiusKm must be between 1 and 50');const blocks=await this.db.block.findMany({where:{OR:[{blockerId:uid},{blockedId:uid}]}});const hidden=blocks.map(b=>b.blockerId===uid?b.blockedId:b.blockerId);const rows=await this.db.hangout.findMany({where:{hostUserId:{notIn:hidden},status:{in:[HangoutStatus.OPEN,HangoutStatus.FULL]},...([30,60,180].includes(m)?{startAt:{lte:new Date(Date.now()+m*60000+90000)}}:{})},orderBy:{startAt:'asc'},include:this.inc(uid)});const statuses=await this.hostStatuses.forUsers(rows.map(r=>r.hostUserId));return rows.map(r=>this.show({...r,host:{...r.host,hostStatus:statuses.get(r.hostUserId)}},uid,lat,lng)).filter(r=>r.distanceKm===null||r.distanceKm<=radius).sort((a,b)=>lat===undefined?new Date(a.startAt).getTime()-new Date(b.startAt).getTime():(a.distanceKm??Infinity)-(b.distanceKm??Infinity))}
 async get(uid:string,id:string){const r=await this.db.hangout.findUnique({where:{id},include:this.inc(uid)});if(!r)throw new NotFoundException();const status=await this.hostStatuses.forUser(r.hostUserId);return this.show({...r,host:{...r.host,hostStatus:status}},uid)}
 async update(uid:string,id:string,x:UpdateHangoutDto){await this.host(uid,id);return this.db.hangout.update({where:{id},data:x})}
 async cancel(uid:string,id:string){await this.host(uid,id);return this.db.hangout.update({where:{id},data:{status:HangoutStatus.CANCELLED}})}
 async finish(uid:string,id:string){const h=await this.db.hangout.findUnique({where:{id}});if(!h)throw new NotFoundException();if(h.hostUserId!==uid)throw new ForbiddenException();const host=await this.db.user.findUnique({where:{id:uid},select:{email:true}});const publicDemo=process.env.DEMO_MODE==='true'&&host?.email.endsWith('@hangoutnow.example');if(h.startAt.getTime()>Date.now()&&!publicDemo)throw new ConflictException('Hangout開始時刻より前には終了できません');if(h.status===HangoutStatus.FINISHED||h.status===HangoutStatus.CANCELLED)throw new ConflictException('Hangout cannot be finished');return this.db.hangout.update({where:{id},data:{status:HangoutStatus.FINISHED}})}
 async rate(uid:string,id:string,x:RateParticipantDto){const h=await this.db.hangout.findUnique({where:{id},include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED}}}});if(!h)throw new NotFoundException();if(h.status!==HangoutStatus.FINISHED)throw new ConflictException('Hangout must be finished before rating');const memberIds=new Set([h.hostUserId,...h.joinRequests.map(r=>r.userId)]);if(!memberIds.has(uid)||!memberIds.has(x.ratedUserId))throw new ForbiddenException('Only participants can rate each other');if(uid===x.ratedUserId)throw new BadRequestException('You cannot rate yourself');return this.db.hangoutRating.upsert({where:{hangoutId_raterUserId_ratedUserId:{hangoutId:id,raterUserId:uid,ratedUserId:x.ratedUserId}},create:{id:uuidv7(),hangoutId:id,raterUserId:uid,ratedUserId:x.ratedUserId,score:x.score},update:{score:x.score}})}
 async join(uid:string,id:string,x:JoinHangoutDto){const h=await this.db.hangout.findUnique({where:{id},include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED}}}});if(!h)throw new NotFoundException();const user=await this.db.user.findUnique({where:{id:uid},select:{birthDate:true,gender:true}});if(!user)throw new NotFoundException();if(h.genderRestriction!==GenderRestriction.ANY){const required=h.genderRestriction===GenderRestriction.MALE_ONLY?Gender.MALE:Gender.FEMALE;if(user.gender!==required)throw new ForbiddenException('このHangoutの性別条件を満たしていません')}if(h.maxAge!==null&&this.age(user.birthDate)>h.maxAge)throw new ForbiddenException('このHangoutの年齢条件を満たしていません');if(await this.db.block.findFirst({where:{OR:[{blockerId:uid,blockedId:h.hostUserId},{blockerId:h.hostUserId,blockedId:uid}]}}))throw new ForbiddenException('Blocked relationship');if(h.hostUserId===uid)throw new BadRequestException('Host cannot join own Hangout');if(h.status!==HangoutStatus.OPEN)throw new ConflictException('Hangout is not open');if(h.joinRequests.length+1>=h.maxParticipants)throw new ConflictException('Hangout is full');try{const out=await this.db.joinRequest.create({data:{id:uuidv7(),hangoutId:id,userId:uid,message:x.message},include:{user:{select:{displayName:true}}}});await this.notifications.notify(h.hostUserId,'JOIN_REQUEST','参加申請が届きました',`${out.user.displayName}さんが「${h.title}」への参加を希望しています。`,`hangout:${id}`,`join:${out.id}`);return out}catch{throw new ConflictException('Join request already exists')}}
 async requests(uid:string,id:string){await this.host(uid,id);return this.db.joinRequest.findMany({where:{hangoutId:id},include:{user:{select:{id:true,displayName:true,verification:true,profilePhoto:true}}}})}
 async decide(uid:string,rid:string,accept:boolean){const r=await this.db.joinRequest.findUnique({where:{id:rid},include:{hangout:{include:{joinRequests:{where:{status:JoinRequestStatus.ACCEPTED}}}}}});if(!r)throw new NotFoundException();if(r.hangout.hostUserId!==uid)throw new ForbiddenException();if(r.status!==JoinRequestStatus.PENDING)throw new ConflictException('Already decided');if(accept&&r.hangout.joinRequests.length+1>=r.hangout.maxParticipants)throw new ConflictException('Hangout is full');const out=await this.db.$transaction(async tx=>{const result=await tx.joinRequest.update({where:{id:rid},data:{status:accept?JoinRequestStatus.ACCEPTED:JoinRequestStatus.REJECTED}});if(accept){await tx.chatRoom.upsert({where:{hangoutId:r.hangoutId},create:{id:uuidv7(),hangoutId:r.hangoutId},update:{}});if(r.hangout.joinRequests.length+2>=r.hangout.maxParticipants)await tx.hangout.update({where:{id:r.hangoutId},data:{status:HangoutStatus.FULL}})}return result});await this.notifications.notify(r.userId,accept?'JOIN_ACCEPTED':'JOIN_REJECTED',accept?'参加が承認されました':'参加申請の結果',`「${r.hangout.title}」の参加申請が${accept?'承認':'見送り'}となりました。`,`hangout:${r.hangoutId}`,`decision:${rid}`);return out}
 private async host(uid:string,id:string){const h=await this.db.hangout.findUnique({where:{id}});if(!h)throw new NotFoundException();if(h.hostUserId!==uid)throw new ForbiddenException()}
 private inc(uid:string){return{host:{select:{id:true,displayName:true,verification:true,profilePhoto:true}},joinRequests:{where:{OR:[{status:JoinRequestStatus.ACCEPTED},{userId:uid}]},select:{userId:true,status:true}}}}
 private show<T extends{hostUserId:string;latitude:number|null;longitude:number|null;publicLatitude:number|null;publicLongitude:number|null;joinRequests:Array<{userId:string;status:JoinRequestStatus}>}>(r:T,uid:string,viewerLat?:number,viewerLng?:number){const exact=r.hostUserId===uid||r.joinRequests.some(j=>j.userId===uid&&j.status===JoinRequestStatus.ACCEPTED);const distanceKm=viewerLat===undefined||viewerLng===undefined||r.publicLatitude===null||r.publicLongitude===null?null:this.distance(viewerLat,viewerLng,r.publicLatitude,r.publicLongitude);return{...r,latitude:exact?r.latitude:undefined,longitude:exact?r.longitude:undefined,locationPrecision:exact?'EXACT':'APPROXIMATE',distanceKm,participantCount:1+r.joinRequests.filter(j=>j.status===JoinRequestStatus.ACCEPTED).length,myJoinStatus:r.joinRequests.find(j=>j.userId===uid)?.status??null}}
 private age(birthDate:Date){const today=new Date();let age=today.getUTCFullYear()-birthDate.getUTCFullYear();if(today.getUTCMonth()<birthDate.getUTCMonth()||(today.getUTCMonth()===birthDate.getUTCMonth()&&today.getUTCDate()<birthDate.getUTCDate()))age-=1;return age}
 private distance(lat1:number,lng1:number,lat2:number,lng2:number){const rad=(n:number)=>n*Math.PI/180;const a=Math.sin(rad(lat2-lat1)/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(rad(lng2-lng1)/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))*10)/10}
}
